insert into teams (name) values ('toskam');
insert into teams (name) values ('mosa climbersm');
insert into users (username, name) values ('mat@luk.fr', 'math');
insert into users (username, name) values ('john@doen.fr', 'John');
insert into users (username, name) values ('lebron@james.fr', 'Lebron');
insert into memberships (user_id, team_id) values (1, 1);
insert into memberships (user_id, team_id) values (1, 2);
insert into memberships (user_id, team_id) values (2, 1);
insert into memberships (user_id, team_id) values (3, 2);
insert into user_notes (user_id, note_id) values (1, 4);
insert into user_notes (user_id, note_id) values (1, 5);